config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-alert:
      branch: master
      repo: https://github.com/ARGOeu/argo-alert.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-alert git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-linen-beetle.sh
        container: qc.acc_fuzzy-eggplant-birman
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-alert find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-brass-caracal.sh
        container: qc.doc_cloudy-seashell-whale
      github.com/ARGOeu/argo-alert git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pumpkin-ladybird.sh
        container: qc.doc_gamy-amber-bee
      github.com/ARGOeu/argo-alert markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cobalt-drever.sh
        container: qc.doc_lanky-apricot-cougar
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-alert licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-rose-coyote.sh
        container: qc.lic_goopy-apricot-fowl
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-alert bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-magnolia-shrew.sh
        container: qc.sec_pokey-dandelion-robin
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-alert flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-khaki-capuchin.sh
        container: qc.sty_hasty-aquamarine-slug
      github.com/ARGOeu/argo-alert jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chartreuse-collie.sh
        container: qc.sty_sleazy-amethyst-rattlesnake
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-alert pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tomato-zonkey.sh
        container: qc.uni_snappy-auburn-tamarin
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-alert get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-rose-devil.sh
        container: qc.ver_snoopy-ultramarine-mandrill
timeout: 5400
